spring.application.name=eureka-server
server.port=8761
spring.config.import=optional:configserver:http://config.platform:8888

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://vm-node-a.platform:8761/eureka,http://vm-node-b.platform:8761/eureka,http://vm-node-c.platform:8761/eureka

eureka.server.enable-self-preservation=false